resources:  
  - name: repo
    type: git
    source:
      uri: ((git-uri))
      branch: master
      username: ((git-username))
      password: ((git-password))
  - name: version
    type: semver
    source:
      initial_version: 1.0.0
      driver: git
      uri: ((git-ci-uri))
      branch: master
      file: ((app))-version
      git_user: "CI Bot <cibot@foobar.com>"
      username: ((git-username))
      password: ((git-password))
  - name: github-prerelease
    type: github-release
    source:
      owner: ((github-owner))
      repository: ((github-repo))
      access_token: ((github-access-token))
      release: false
      pre_release: true
  - name: cf
    type: cf
    source:
      api: ((cf-api))
      username: ((cf-username))
      password: ((cf-password))
      organization: ((cf-org))
      space: ((cf-space))

jobs:
  - name: build
    plan:
    - get: repo
      trigger: true
    - get: version
      params:
        bump: patch
    - task: build
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: adoptopenjdk
            tag: 8-jdk-hotspot
        params:
          APP: ((app))
        inputs:
          - name: repo
          - name: version
        outputs:
          - name: build
        caches:
          - path: .m2
        run:
          path: "repo/ci/tasks/build.sh"
    - put: github-prerelease
      params:
        name: build/release
        tag: version/number
        tag_prefix: v
        globs: [ "build/((app))-*.jar", "build/manifest.yml" ]
    - put: version
      params:
        file: version/number

  - name: deploy
    plan:
    - get: github-prerelease
      trigger: true
      params:
        globs: [ "((app))-*.jar", "manifest.yml" ]
    - put: cf
      params:
        manifest: ../get/manifest.yml
        current_app_name: ((app))
